steps:
  build:
    image: golang:1.22
    commands:
      - go mod tidy
      - go build -o gospt-ng

  publish:
    image: goreleaser/goreleaser:nightly
    commands:
      - goreleaser release --clean
    secrets: [ gitea_token ]
    when:
      event: tag
