name: build-binary
run-name: ${{ gitea.actor }} is building
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true
      - run: go mod tidy
      - run: go build -o gspot
